sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

php:
  - 5.2
  - 5.3
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=0
  - WP_VERSION=4.7.3 WP_MULTISITE=0

script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi 2>&1
